config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
    
  scope '/', module: :web, as: :web do
    root to: 'home#index'
    resources :posts do 
      collection do
        get '/random' => 'posts#random'
      end
    end
    # get '/posts/random' => 'posts#random'
  end
  scope '/vocabulary', module: :web, as: :web do
    root to: 'vocabulary#index'
    
  end
  scope '/vocabulary/random', module: :web, as: :web do
    root to: 'random#random'
    
  end
  scope '/admin', module: :admin, as: :admin do
    root to: 'admin#home'
    resources :posts
  end
  # For details on the DSL a vailable within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_attached_file :mp3
  validates_attachment :mp3,
    :content_type => { :content_type => ["audio/mpeg", "audio/mp3"] },
    :file_name => { :matches => [/mp3\Z/] }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def username_def
    email.split('@')[0]
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < AdminController
  def home

  end
end

app/controllers/admin/posts_controller.rb
# frozen_string_literal: true
class Admin::PostsController < AdminController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authenticate_user!,  except: [:show,:index]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
     @post = Post.find_by_id(params[:id])
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to admin_post_path(@post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to admin_post_path(@post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to admin_posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:vocabulary, :mp3)
  end

  

end

app/controllers/admin_controller.rb
# frozen_string_literal: true

class AdminController < ApplicationController

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[show index]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show; end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:vocabulary)
  end
end

app/controllers/web/home_controller.rb
class Web::HomeController < WebController
  def index
    
  end
end

app/controllers/web/posts_controller.rb
class Web::PostsController < WebController
  
  def index
    @posts = Post.all
  end
  def show
    
  end
  def random
    # @post = Post.offset(rand(Post.count)).first
    # @post = Post.find_by_id(params[:id])
     @posts = Post.offset(rand(Post.count)).limit(1)
    #  puts @posts.to_json
  end
  
end

app/controllers/web/random_controller.rb
class Web::RandomController < WebController

  def random
     @posts = Post.all
  end
 end 

app/controllers/web/vocabulary_controller.rb
class Web::VocabularyController < WebController

  def index
     @posts = Post.all
  end

 end 

app/controllers/web_controller.rb
# frozen_string_literal: true

class WebController < ApplicationController
  
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/dashboard/home.html.erb
<h1>hello</h1>
<% if current_user %>
<%= link_to 'View Post', admin_posts_path %>
<%= link_to 'New Post', new_admin_post_path %>
<%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
<% else %>
<%= link_to 'View Post', admin_posts_path %>
<%= link_to 'Sign In', new_user_session_path %>
<%= link_to 'Sign Up', new_user_registration_path %>
<% end %>

app/views/admin/posts/_form.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col">
      <%= form_with(model: [:admin, @post], local: true,class: :'form-group') do |form| %>
      <% if post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
          <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>

      <div class="field">
        <%= form.label :'Type vocabulary:' %>
        <%= form.text_field :vocabulary, class: :"form-control" %>
      </div>

      <div class="field">
        <%= form.label :'Add audio' %>
        <%= form.file_field :mp3  , class: :"form-control" %>
      </div>

      <div class="actions">
        <%= form.submit 'Add new',:class => 'btn btn-primary mt-4' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/posts/edit.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-12 col-md-8 col-lg-12 ">
      <h1>Editing Vocabulary</h1>
      <%= render 'form', post: @post %>
    </div>
  </div>
  <div class="row">
    <div class="container text-center">
      <%= link_to 'View', admin_post_path(@post),:class => 'btn btn-warning mt-4' %>
      <%= link_to 'Back', admin_posts_path, :class => 'btn btn-success mt-4' %>
    </div>
  </div>
</div>

app/views/admin/posts/index.html.erb
<section class="bg-warning text-white py-5 mb-5">
  <div class="container text-center">
    <h1>ADD VOCABULARY TO LIBRARY</h1>
    <p class="lead">Starting points for finding information on learning English as a second language.</p>
  </div>
</section>
<div class="container">
  <div class="row">
    <div class="col">
      <p id="notice"><%= notice %></p>
      <table class="table table-stripe text-center">
        <thead class="thead-dark">
          <tr>
            <th>Vocabulary</th>
            <th>User</th>
            <th>Detail Vocabulary</th>
            <% if (current_user) %>
            <th>Edit Vocabulary</th>
            <th>Delete Vocabulary</th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <% @posts.each do |post| %>
          <tr>
            <td><%= post.vocabulary %></td>
            <td><%= post.user.username_def %></td>
            <td><%= link_to 'Show', admin_post_path(post),:class => "btn btn-info mr-2" %></td>
            <% if current_user && current_user %>
            <td><%= link_to 'Edit', edit_admin_post_path(post),:class => "btn btn-warning mr-2" %></td>
            <td>
              <%= link_to 'Delete', admin_post_path(post), method: :delete, data: { confirm: 'Are you sure?' },:class => "btn btn-danger mr-2" %>
            </td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<!-- ---------- -->
<div class="container">
  <div class="row">
    <div class="col text-center">
      <% if current_user %>
      <%= link_to 'New Post', new_admin_post_path, :class => "btn btn-primary mr-2" %>
      <%= link_to 'Sign Out', destroy_user_session_path, method: :delete,:class => "btn btn-danger mr-2" %>
      <% else %>
      <%= link_to 'Sign In', new_user_session_path,:class => "btn btn-primary mr-2" %>
      <%= link_to 'Sign Up', new_user_registration_path,:class => "btn btn-warning mr-2" %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/posts/new.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col">
      <h1>New Vocabulary</h1>
      <%= render 'form', post: @post %>
      <div class="row">
        <div class="container text-center">
          <%= link_to 'Back', admin_posts_path,:class => 'btn btn-danger mt-4' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/posts/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col">
      <p id="notice"><%= notice %></p>
      <!-- <%= @post %> -->
      <h3>
        <strong>New word:</strong>
        <%= @post.vocabulary %>
      </h3>
      <p>
        <strong>User create:</strong>
        <%= @post.user.username_def %>
      </p>
    </div>
  </div>
</div>
<div class="row">
  <div class="container text-center">
    <%= link_to 'Edit', edit_admin_post_path(@post),:class => 'btn btn-warning mt-4' %>
    <%= link_to 'Back', admin_posts_path,:class => 'btn btn-success mt-4' %>
  </div>
</div>
</div>
<div class="container mt-5">
  <div class="row">
    <div class="col">
      <% if @post.mp3.present? %>
      <%= audio_tag(@post.mp3, controls:true, style:"width:100%") %>
      <% end %>
    </div>
  </div>
</div>

app/views/admins/home.html.erb
<h1>hello</h1>
<% if current_user %>
<%= link_to 'View Post', posts_path %>
<%= link_to 'New Post', new_post_path %>
<%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
<% else %>
<%= link_to 'View Post', posts_path %>
<%= link_to 'Sign In', new_user_session_path %>
<%= link_to 'Sign Up', new_user_registration_path %>
<% end %>

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert  %></p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">VOA</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto ">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/admin/posts">Add Vocabulary</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/vocabulary">View Vocabulary</a>
      </li>
      <% if current_user %>
      <li class="nav-item">
        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete,:class => "nav-link" %>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to 'Sign In', new_user_session_path,:class => "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Sign Up', new_user_registration_path,:class => "nav-link" %>
      </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>VocabularyApp</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render 'layouts/navbar' %>
  <%= yield %>
  <div class="container">
    <div class="row">
      <div class="col">
        <%= render 'layouts/alerts' %>
      </div>
    </div>
  </div>
</body>

</html>

app/views/web/home/index.html.erb
<section class="bg-warning text-white py-5 mb-5">
  <div class="container text-center">
    <h1>Welcome to Vocabulary Library</h1>
    <p class="lead">Starting points for finding information on learning English as a second language.</p>
  </div>
</section>

<section id="about">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 mx-auto">
        <h2>About this page</h2>
        <p class="lead">This is a great place to talk about your webpage. This template is purposefully unstyled so you
          can use it as a boilerplate or starting point for you own landing page designs! This template features:</p>
        <ul>
          <li>Clickable nav links that smooth scroll to page sections</li>
          <li>Responsive behavior when clicking nav links perfect for a one page website</li>
          <li>Bootstrap's scrollspy feature which highlights which section of the page you're on in the navbar</li>
          <li>Minimal custom CSS so you are free to explore your own unique design options</li>
        </ul>
      </div>
    </div>
  </div>
</section>

app/views/web/posts/index.html.erb
xxxindex

<%=@posts %>

yyy

app/views/web/posts/random.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col text-center">
      <% @posts.each do |post| %>
      <tr>
        <td>
          <h4>Auto vocabulary: <%= post.vocabulary %></h4>
        </td>
        <td>
          <p class="text-primary">
            User create: <%= post.user.username_def %></p>
        </td>
      </tr>
      <div class="row">
        <div class="col">
          <% if post.mp3.present? %>
          <%= audio_tag(post.mp3, controls:true, style:"width:50%") %>
          <% end %>
        </div>
      </div>
      <% end %>
      <%= link_to 'Generate Vocabulary', random_web_posts_path,:class => 'btn btn-warning mt-4' %>
    </div>
  </div>
</div>

app/views/web/random/random.html.erb
<section class="bg-warning text-white py-5 mb-5">
  <div class="container text-center">
    <h1>RANDOM VOCABULARY</h1>
  </div>
</section>
<div class="container">
  <div class="row">
    <div class="col text-center">
      <button class="btn btn-success ">Random Vocabulary</button>
      <% @posts.each do |post| %>
      <script>
        // var arr = [...post]
        console.log(post)
      </script>
      <%= link_to 'Show', admin_post_path(post),:class => "btn btn-success mr-2" %>
      <% end %>
    </div>
  </div>
</div>

app/views/web/vocabulary/index.html.erb
<section class="bg-warning text-white py-5 mb-5">
  <div class="container text-center">
    <h1>VOCABULARY LIBRARY</h1>
    <p class="lead">Starting points for finding information on learning English as a second language.</p>
  </div>
</section>
<div class="container">
  <div class="row">
    <div class="col">
      <p id="notice"><%= notice %></p>
      <table class="table table-stripe text-center">
        <thead class="thead-dark">
          <tr>
            <th>Vocabulary</th>
            <th>User</th>
            <th>Detail Vocabulary</th>
          </tr>
        </thead>
        <tbody>
          <% @posts.each do |post| %>
          <tr>
            <td><%= post.vocabulary %></td>
            <td><%= post.user.username_def %></td>
            <td><%= link_to 'Show', admin_post_path(post),:class => "btn btn-info mr-2" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>